### ISSUE TITLE
GetExcelDataType returns Numeric for date formatted cells

### ISSUE THREAD

**Issue by xnmf** [MarkPflug/Sylvan.Data.Excel#165]
I am planning to use your lib for a project, but as I am testing it on some test data I get an issue using the .GetExcelDataType(i) method, it seems to consistently return the type Numeric for cells formated as Datetime.

Am I missing something basic? Is there a better way to determine if a cell should be interpreted as datetime?

Using the .GetString method returns a correctly formatted datetime string.

Example data available below:
https://www.contextures.com/tablesamples/sampledatasafety.zip

**Comment by MarkPflug** [comment]
That is correct and expected behavior. Internally, "date" values in Excel are stored as numbers which are formatted to be displayed as a datetime format. You can use the ExcelDataReader.GetFormat(int ordinal) to get the format info for a cell, then check the ExcelFormat.Kind property which will indicate if the format is Numeric, Date or Time.
