### ISSUE TITLE
System.ArgumentOutOfRangeException: 'Index was out of range. (xlsx file)

### ISSUE THREAD

**Issue by 0x410c** [MarkPflug/Sylvan.Data.Excel#30]
This exception was originally thrown at this call stack:
    System.ThrowHelper.ThrowArgumentOutOfRange_IndexException()
    System.Collections.Generic.List<T>.this[int].get(int)
    System.Collections.ObjectModel.ReadOnlyCollection<T>.this[int].get(int)
    Sylvan.Data.Excel.XlsxWorkbookReader.IsDBNull(int)
    Sylvan.Data.Excel.ExcelDataReader.GetValue(int)

**Comment by MarkPflug** [comment]
I think all the issues you've had should be fixed with 0.1.8-b0003, which I just pushed to nuget.
It looks like have been using `GetValue` to access values. One thing to be aware of with that: `GetValue` will return values that are typed to the "schema" of the ExcelDataReader. By default, the schema is that every column will be read as a nullable string. The behavior of the `GetValue` method cannot be changed, because it is required to comply with the contracts that are expected of the base `DbDataReader` type. I've added `GetExcelValue`, which will return the value of the cell as represented in Excel. However, if you know the data type that is expected in a column, it is best to use the strongly-typed accessors GetDouble, GetDateTime, etc, as those are the most efficient; they don't box the values.

**Comment by MarkPflug** [comment]
I've added some general-purpose tests that demonstrate code that is expected to work for all files, [you can see that code here](https://github.com/MarkPflug/Sylvan.Data.Excel/blob/96192689abde1d1ac2ec026f62a58d6a9d6b2603/source/Sylvan.Data.Excel.Tests/ExternalDataTests.cs#L32-L61)
To use these tests, set the environment variable `SylvanExcelTestData` to point to a folder containing excel files. Then when you run the tests it will verify that every file in the folder doesn't fail for this standard access patterns.
