### ISSUE TITLE
Error #N/A #N/D

### ISSUE THREAD

**Issue by bmore-marcoscarrillo** [MarkPflug/Sylvan.Data.Excel#41]
Hi, I found this bug, when I have this Cell (#N/D), return a exception
![image](https://user-images.githubusercontent.com/90401887/155633872-79c8b71c-70da-47f5-a7bd-82037c3ee607.png)

kind regards

**Comment by MarkPflug** [comment]
This is expected when the spreadsheet has an error in it.
You can call `GetExcelDataType(int ordinal)` and if the value is `ExcelDataType.Error` then accessing the value in that cell is expected to throw an `ExcelFormulaException`. You can also set `GetErrorAsNull = true` to make it so that all errors are ignored, and the cell will be treated as if it were blank.
```
var opts = new ExcelDataReaderOptions { GetErrorAsNull = true };
var edr = ExcelDataReader.Create("file.xlsx", opts);
```

**Comment by bmore-marcoscarrillo** [comment]
Excelent, Thanks...
I discovered the options when I load a stream
