### ISSUE TITLE
How to specify custom header row?

### ISSUE THREAD

**Issue by sacalata** [MarkPflug/Sylvan.Data.Excel#58]
I have the following function to read an xlsx file as an datatable
```
public static DataTable GetDataTableFromExcelFile(Stream stream, string sheetName, ExcelWorkbookType format)
        {
            var dt = new DataTable();
            var dataReader = ExcelDataReader.Create(stream, ExcelWorkbookType.ExcelXml);
            while (dataReader.WorksheetName != sheetName && dataReader.NextResult());
            dt.Load(dataReader);
            return dt;
        }
```
this uses the first row as header, how can i specify a custom row number to be used as header?

**Comment by MarkPflug** [comment]
Question for you: what are you expecting to be loaded in the DataTable? The string value of every column, or strongly-typed columns, like numbers, dates, bool, etc?

**Comment by MarkPflug** [comment]
As of 0.2.0-b0001 (pre-release), you can call dataReader.Initialize() to cause the data reader to reinitialize the header/schema. It is up to you to position the reader on the appropriate row, since there is no way for the library to know what that might be. So, you'd call Read() until you find the appropriate row, then call Initialize(). After that you should be able to call DataTable.Load to load the remaining rows in the datatable.

I will be pushing a final 0.2.0 package in the next few days.
